name: Node.js CI
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 20.9.0
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Enable corepack
        run: corepack enable
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"
          cache: yarn
          registry-url: "https://registry.yarnpkg.com"

      - name: Set yarn version
        run: yarn set version stable
      - name: Install dependencies
        run: yarn install --immutable
      - name: build
        run: yarn build
      - name: lint:check
        run: yarn lint:check
      - name: test
        run: yarn test
      - name: Setup token
        run: 'echo "npmAuthToken: ${NPM_TOKEN}" >> ~/.yarnrc.yml'
      - name: publish
        run: yarn npm publish
